### ISSUE TITLE
License file missing?

### ISSUE THREAD

**Issue by theolivenbaum** [arkivujo/Arkivujo.Alfresco.Api#1]
Hi @arkivujo, nice work with the port! Just wanted to check regarding the license for the code. 

The [project files](https://github.com/arkivujo/Arkivujo.Alfresco.Api/blob/f9eb55037762b7bf19d1559a7d5e289d08e64043/Arkivujo.Alfresco.Search/Arkivujo.Alfresco.Search.csproj#L12) seem to indicate BSD-3, but I couldn't find any license file in the repository...

**Comment by roblthegreat** [comment]
@theolivenbaum Thank you for pointing out the omission.  Sorry about the slow response.  This was a personal project and I haven't had much time to devote to project.  You are correct, the license should be BSD 3-clause.  I have added a license file for clarification and committed it to the repository.

However, be aware that this repository will be archived.  My original need for this API wrapper no longer exists and I am unable to devote time into continuing to develop or maintain the code.
